# Generated by Django 5.0.6 on 2024-07-04 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_latitude', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid latitude with up to 6 decimal places.', regex='^-?\\d{1,2}\\.\\d{1,6}$')])),
                ('source_longitude', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid longitude with up to 6 decimal places.', regex='^-?\\d{1,2}\\.\\d{1,6}$')])),
                ('destination_latitude', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid latitude with up to 6 decimal places.', regex='^-?\\d{1,2}\\.\\d{1,6}$')])),
                ('destination_longitude', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid longitude with up to 6 decimal places.', regex='^-?\\d{1,2}\\.\\d{1,6}$')])),
                ('trip_date', models.DateField()),
                ('trip_time', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.profile')),
            ],
        ),
    ]
